force-app/main/default/objects/Account/fields/Shipping_Order__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Order</label>
    <referenceTo>Shipping_Order__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Order__c/Shipping_Order__c.object-meta.xml
<CustomObject>
    <label>Shipping Order</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{DD}-{00000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Order__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Port</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shipping Orders (Account-Order)</relationshipLabel>
    <relationshipName>Shipping_Orders1</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Shipping_Order__c/fields/Planned_TEU__c.field-meta.xml
<CustomField>
    <fullName>Planned_TEU__c</fullName>
    <label>Planned TEU</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipping_Order__c/fields/Shipping_Project__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Project__c</fullName>
    <label>Shipping Project</label>
    <referenceTo>Shipping_Project__c</referenceTo>
    <relationshipLabel>Shipping Orders</relationshipLabel>
    <relationshipName>Shipping_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Shipping_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipping_Project__c/Shipping_Project__c.object-meta.xml
<CustomObject>
    <label>Shipping Project</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{DD}-SP#{00000}</displayFormat>
        <label>Shipping project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Loading</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestTaskCreation.cls
@isTest
public with sharing class TestTaskCreation {

@isTest static void testCreateTaskAfterOrder(){

        Test.startTest();
        Account account = new Account(Name = 'Test Account');
        Database.SaveResult resultAccount = Database.insert(account);

        Shipping_Project__c shippingProject = new Shipping_Project__c();
        Database.SaveResult resultsShippingProject = Database.insert(shippingProject);

        List<Shipping_Order__c> orders = new List<Shipping_Order__c>();

        for (Integer i = 0; i < 300; i++) {

            Shipping_Order__c order = new Shipping_Order__c();
            order.Status__c  ='New';
            order.Shipping_Project__c = shippingProject.id;
            order.Customer__c = account.id;
            order.Planned_TEU__c = i;
            orders.add(order);
        }

        List<Database.SaveResult> results = Database.insert(orders);

        for (Database.SaveResult result : results) {
            System.assertEquals(true, result.isSuccess());
        }

        List<Task> tasks = [SELECT Id, Status, Subject, Priority, WhatId, Description, OwnerId FROM Task];
        
        System.assertEquals(300, tasks.size());

        Task testedTask = tasks.get(1);
        System.assertEquals('New', testedTask.Status);
        System.assertEquals('Other', testedTask.Subject);
        System.assertEquals('Normal', testedTask.Priority);
        System.assertEquals(account.Id, testedTask.WhatId);
        System.assert(testedTask.Description.startsWith('New order has been created'));

        Test.stopTest();
        
    }
}